#Ryzhova Oleksandra
 a = 10/2
 print("10/2 = " + str(a))
 print("Type of result:")
 print(type(a))
 b = 144/1.2
 print("144/1.2 = " + str(b))
 print("Type of result:")
 print(type(b))
 c = 34/(-2)
 print("34/(-2) = " + str(c))
 print("Type of result:")
 print((type(c)))
 print('')
 d = 113%24
 print("113%24 = " + str(d))
 print("Type of result:")
 print(type(d))
 e = 144%1.8
 print("144%1.8 = " + str(e))
 print("Type of result:")
 print(type(e))
 f = 34%(-7)
 print("34%(-7) = " + str(f))
 print("Type of result:")
 print((type(f)))
 print('')
 j = 174//84
 print("174//84 = " + str(j))
 print("Type of result:")
 print(type(j))
 i = 37//13.4
 print("37//13.4 = " + str(i))
 print("Type of result:")
 print(type(i))
 k = 832//(-94)
 print("832//(-94) = " + str(k))
 print("Type of result:")
 print((type(k)))
 print('')
 l = 3**4
 print("3**4 = " + str(l))
 print("Type of result:")
 print(type(l))
 m = 1.7**5
 print("1.7**5 = " + str(m))
 print("Type of result:")
 print(type(m))
 o = 144**(0.5)
 print("144**(0.5) = " + str(o))
 print("Type of result:")
 print((type(o)))
 n = (-5)**3
 print("(-5)**3 = " + str(n))
 print("Type of result:")
 print((type(n)))
 print('')
 print("Binary ---> decimal")
 print("0b1110101 = " + str(int('0b1110101',2)))
 print("Octal ---> decimal")
 print("0o1042 = " + str(int('0o1042',8)))
 print("Hex ---> decimal")
 print("0xa2 = " + str(int('0xa2',16)))
